'use strict';
const express = require('express');

module.exports = function devotionalRoutes(ctx) {
  const router = express.Router();
  const { pool, authenticate, openai, pexels, generateDailyDevotional, sendDailyDevotionalNotification, dailyBreadAudioCache, DEVOTIONAL_AUDIO_DIR, loadFaithRanks, awardBadge, log, fs, path, serveAudioBuffer } = ctx;

router.post('/getDailyBreadAudio', async (req, res) => {
  try {
    const { date, title, content, bibleVerse, verseReference, prayer, checkOnly, lang = 'en' } = req.body;

    if (!date) {
      return res.status(400).json({ message: "date is required" });
    }

    const isEs = lang === 'es';
    const cacheKey = isEs ? `${date}_es` : date;
    const audioFileName = isEs ? `daily_bread_${date}_es.mp3` : `daily_bread_${date}.mp3`;
    const prayerIntro = isEs ? 'Oración de cierre de hoy.' : 'Today\'s closing prayer.';

    // checkOnly mode — return JSON status without serving audio (useful for Postman testing)
    if (checkOnly) {
      const cached = dailyBreadAudioCache.has(cacheKey);
      return res.json({
        success: true,
        date,
        lang,
        cached,
        message: cached ? "Audio already cached for this date" : "Audio not yet cached — will be generated on next real request"
      });
    }

    // Serve from in-memory cache if available
    if (dailyBreadAudioCache.has(cacheKey)) {
      console.log(`🔊 Daily Bread audio cache hit for ${date} [${lang}]`);
      return serveAudioBuffer(req, res, dailyBreadAudioCache.get(cacheKey));
    }

    // Serve from disk if pre-generated by cron
    const audioPath = path.join(DEVOTIONAL_AUDIO_DIR, audioFileName);
    if (fs.existsSync(audioPath)) {
      console.log(`🔊 Daily Bread audio served from disk for ${date} [${lang}]`);
      const audioBuffer = fs.readFileSync(audioPath);
      dailyBreadAudioCache.set(cacheKey, audioBuffer);
      return serveAudioBuffer(req, res, audioBuffer);
    }

    // Compose the TTS script and generate on-demand
    let text = [
      title || '',
      bibleVerse && verseReference ? `${bibleVerse} — ${verseReference}` : (bibleVerse || verseReference || ''),
      content || '',
      prayer ? `${prayerIntro} ${prayer}` : ''
    ]
      .filter(Boolean)
      .join('\n\n')
      .slice(0, 4000);

    console.log(`🔊 Generating Daily Bread audio for ${date} [${lang}] (${text.length} chars)...`);

    const ttsResponse = await openai.audio.speech.create({
      model: 'tts-1-hd',
      voice: 'nova',
      input: text,
      response_format: 'mp3'
    });

    const audioBuffer = Buffer.from(await ttsResponse.arrayBuffer());
    dailyBreadAudioCache.set(cacheKey, audioBuffer);
    console.log(`🔊 Daily Bread audio generated and cached for ${date} [${lang}] (${audioBuffer.length} bytes)`);

    serveAudioBuffer(req, res, audioBuffer);

  } catch (error) {
    console.error('Daily Bread audio generation error:', error);
    res.status(500).json({ message: "Failed to generate audio" });
  }
});

router.get('/getFaithRanks', async (req, res) => {
  try {
    const ranks = await loadFaithRanks();
    res.json({ ranks });
  } catch (err) {
    console.error('Error fetching faith ranks:', err);
    res.status(500).json({ error: 'Database error: ' + err.message });
  }
});

// POST /readDailyBread - Award faith points for reading today's Daily Bread (once per day)
router.post('/readDailyBread', authenticate, async (req, res) => {
  try {
    const { userId } = req.body;
    if (!userId) return res.json({ error: 1, result: "Required param 'userId' missing" });

    const todayUTC = new Date().toISOString().slice(0, 10); // 'YYYY-MM-DD'

    const checkResult = await pool.query(
      'SELECT last_daily_bread_date FROM public."user" WHERE user_id = $1',
      [userId]
    );

    if (checkResult.rows.length === 0) {
      return res.json({ error: 1, result: "User not found" });
    }

    const lastRead = checkResult.rows[0].last_daily_bread_date;
    const alreadyRead = lastRead && lastRead.toISOString().slice(0, 10) === todayUTC;

    if (alreadyRead) {
      return res.json({ error: 0, points_awarded: 0, already_read: true });
    }

    // Compute new streak
    const yesterday = new Date();
    yesterday.setUTCDate(yesterday.getUTCDate() - 1);
    const yesterdayStr = yesterday.toISOString().slice(0, 10);
    const lastReadStr = lastRead ? lastRead.toISOString().slice(0, 10) : null;
    const currentStreak = checkResult.rows[0].daily_bread_streak || 0;
    const newStreak = lastReadStr === yesterdayStr ? currentStreak + 1 : 1;

    await pool.query(
      `UPDATE public."user"
       SET faith_points = COALESCE(faith_points, 0) + 2,
           last_daily_bread_date = $1,
           daily_bread_streak = $2
       WHERE user_id = $3`,
      [todayUTC, newStreak, userId]
    );

    // daily_bread_streak badge: 7 consecutive days
    let newBadge = null;
    try {
      if (newStreak >= 7) {
        newBadge = await awardBadge(userId, 'daily_bread_streak');
      }
    } catch (badgeErr) {
      console.warn('Badge check failed (non-blocking):', badgeErr.message);
    }

    return res.json({ error: 0, points_awarded: 2, already_read: false, streak: newStreak, new_badge: newBadge });

  } catch (error) {
    console.error('Error in /readDailyBread endpoint:', error);
    res.json({ error: 1, result: "Internal server error: " + error.message });
  }
});

// GET /getUserBadges - Get all badges earned by a user

router.get('/getDailyDevotional', async (req, res) => {
  try {
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
    let result = await pool.query(
      'SELECT * FROM public.daily_devotional WHERE date = $1 AND lang = $2',
      [today, 'en']
    );

    // Today's article is missing — auto-generate it now (first caller triggers it, everyone else benefits)
    if (result.rows.length === 0) {
      console.log(`📖 No devotional for ${today} — auto-generating on demand...`);
      try {
        await generateDailyDevotional(new Date());
        result = await pool.query(
          'SELECT * FROM public.daily_devotional WHERE date = $1 AND lang = $2',
          [today, 'en']
        );
        // If it's past 8 AM Eastern (12:00 PM UTC), the scheduled notification
        // already missed — send it now as a catch-up for all users
        const utcHour = new Date().getUTCHours();
        if (utcHour >= 12) {
          sendDailyDevotionalNotification('catch-up after on-demand generation').catch(e =>
            console.error('Catch-up notification failed:', e.message)
          );
        }
      } catch (genErr) {
        console.error('On-demand devotional generation failed:', genErr.message);
        // Generation failed — fall back to most recent so the app still works
        result = await pool.query(
          'SELECT * FROM public.daily_devotional ORDER BY date DESC LIMIT 1'
        );
      }
    }

    if (result.rows.length === 0) {
      return res.json({ error: 1, result: 'No devotional available yet.' });
    }

    const row = result.rows[0];
    row.date = new Date(row.date).toISOString().slice(0, 10);
    res.json({ error: 0, result: row });
  } catch (error) {
    console.error('getDailyDevotional error:', error);
    res.status(500).json({ error: 1, result: 'Internal server error' });
  }
});

// POST /getDailyDevotional — mobile app version, supports lang param
router.post('/getDailyDevotional', authenticate, async (req, res) => {
  try {
    const lang = (req.body && req.body.lang === 'es') ? 'es' : 'en';
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' });

    let result = await pool.query(
      'SELECT * FROM public.daily_devotional WHERE date = $1 AND lang = $2',
      [today, lang]
    );

    if (result.rows.length === 0) {
      console.log(`📖 No ${lang} devotional for ${today} — generating on demand...`);
      try {
        await generateDailyDevotional(new Date(), lang);
        result = await pool.query(
          'SELECT * FROM public.daily_devotional WHERE date = $1 AND lang = $2',
          [today, lang]
        );
      } catch (genErr) {
        console.error(`On-demand ${lang} devotional generation failed:`, genErr.message);
        // Fall back to English if Spanish generation fails
        result = await pool.query(
          'SELECT * FROM public.daily_devotional WHERE date = $1 AND lang = $2',
          [today, 'en']
        );
        if (result.rows.length === 0) {
          result = await pool.query(
            'SELECT * FROM public.daily_devotional ORDER BY date DESC LIMIT 1'
          );
        }
      }
    }

    if (result.rows.length === 0) {
      return res.json({ error: 1, result: 'No devotional available yet.' });
    }

    const row = result.rows[0];
    row.date = new Date(row.date).toISOString().slice(0, 10);
    res.json({ error: 0, result: row });
  } catch (error) {
    console.error('POST getDailyDevotional error:', error);
    res.status(500).json({ error: 1, result: 'Internal server error' });
  }
});

// POST /generateDevotional — admin endpoint to manually trigger generation
router.post('/generateDevotional', async (req, res) => {
  try {
    const key = req.body.key || req.headers['x-admin-key'];
    if (key !== process.env.ADMIN_BROADCAST_KEY) {
      return res.status(403).json({ error: 1, result: 'Unauthorized' });
    }
    const targetDate = req.body.date ? new Date(req.body.date) : new Date();
    const dateStr = targetDate.toISOString().slice(0, 10);
    const langParam = req.body.lang; // optional — if omitted, generate both EN + ES

    if (langParam === 'es') {
      // ES only — try to reuse EN image/theme from DB
      const enRow = await pool.query(
        'SELECT theme, image_url FROM public.daily_devotional WHERE date = $1 AND lang = $2',
        [dateStr, 'en']
      );
      const sharedTheme = enRow.rows[0]?.theme || null;
      const sharedImageUrl = enRow.rows[0]?.image_url || null;
      await generateDailyDevotional(targetDate, 'es', { sharedTheme, sharedImageUrl });
    } else if (langParam === 'en') {
      await generateDailyDevotional(targetDate, 'en');
    } else {
      // Generate EN first, then ES with shared context
      const enResult = await generateDailyDevotional(targetDate, 'en');
      await generateDailyDevotional(targetDate, 'es', {
        sharedTheme: enResult.theme,
        sharedImageUrl: enResult.imageUrl
      });
    }

    const saved = await pool.query('SELECT * FROM public.daily_devotional WHERE date = $1', [dateStr]);
    res.json({ error: 0, result: 'Devotional generated', devotionals: saved.rows });
  } catch (error) {
    console.error('Manual devotional generation error:', error);
    res.status(500).json({ error: 1, result: error.message });
  }
});

  return router;
};
